import { Connection } from "@/types";
export const connectionsData: Connection[] = [
  {
    description: "Marketing Suite",
    app: "Gmail",
    client: "Acme Inc",
    accessToken: "ya29_e9...",
    refreshToken: "1//04_5u...",
    expiration: new Date("2025-04-07"),
  },
  {
    description: "Data Sync",
    app: "Shopify",
    client: "TechCorp",
    accessToken: "shpat_t1...",
    refreshToken: "shprt_hk...",
    expiration: new Date("2025-03-28"),
  },
  {
    description: "Integration Hub",
    app: "Slack",
    client: "Design Studio",
    accessToken: "xoxp_c01...",
    refreshToken: "xoxr_2ty...",
    expiration: new Date("2025-03-21"),
  },
  {
    description: "Customer Portal",
    app: "Zendesk",
    client: "Global Services",
    accessToken: "zd_duxn...",
    refreshToken: "zdr_e27...",
    expiration: new Date("2025-04-12"),
  },
  {
    description: "Sales Dashboard",
    app: "HubSpot",
    client: "Retail Solutions",
    accessToken: "pat_sue...",
    refreshToken: "prt_kco...",
    expiration: new Date("2025-03-24"),
  },
  {
    description: "Analytics Platform",
    app: "Google Analytics",
    client: "Marketing Agency",
    accessToken: "UA-13px...",
    refreshToken: "GA-w7hm...",
    expiration: new Date("2025-04-04"),
  },
  {
    description: "File Manager",
    app: "Dropbox",
    client: "Creative Team",
    accessToken: "sl_clwf...",
    refreshToken: "sb_wav8...",
    expiration: new Date("2025-03-18"),
  },
  {
    description: "Social Media Manager",
    app: "Twitter",
    client: "PR Department",
    accessToken: "AAAA_l31...",
    refreshToken: "r-070b...",
    expiration: new Date("2025-03-31"),
  },
  {
    description: "Workflow Automation",
    app: "Microsoft 365",
    client: "Operations Team",
    accessToken: "eyJA_47h...",
    refreshToken: "M.R3_jg0...",
    expiration: new Date("2025-04-17"),
  },
  {
    description: "Project Management",
    app: "Asana",
    client: "Product Team",
    accessToken: "0/_v58b2...",
    refreshToken: "1/_a5j8c...",
    expiration: new Date("2025-03-22"),
  },
  {
    description: "Help Desk",
    app: "Freshdesk",
    client: "Support Team",
    accessToken: "fd_fplu...",
    refreshToken: "fdr_i71...",
    expiration: new Date("2025-03-26"),
  },
  {
    description: "Document Processor",
    app: "DocuSign",
    client: "Legal Department",
    accessToken: "eyJ_n1x...",
    refreshToken: "ref_fph...",
    expiration: new Date("2025-04-10"),
  },
];
